pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npmm2:z
                        -u root
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            stages {
                stage('Installation dependances') {
                    steps {
                        dir('ANGULAR/quest-angular') {
                            sh 'npm install'
                        }
                    }
                }

                stage('Build Angular') {
                    steps {
                        dir('ANGULAR/quest-angular') {
                            sh './node_modules/.bin/ng build'
                        }
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('ANGULAR/quest-angular') {
                    sh 'docker build -t ajc/quest:angular .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                dir('DOCKER/commandes/compose/quest') {
                    sh 'docker compose up -d --build angular'
                }
            }
        }
    }
}
