pipeline {
    agent any

    stages {
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network biblio
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('bibliotek/bibliotek-boot') {
                    sh 'mvn -version'
                    sh 'mvn package'
                }
            }
        }


        stage('Analyse Sonar') {

            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network biblio
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('bibliotek/bibliotek-boot') {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=bibliotek-boot -Dsonar.projectName='bibliotek-boot'"
                    }
                }
            }
        }
    
        stage('Docker Build') {
            steps {
                dir('bibliotek/bibliotek-boot') {
                    sh 'docker build -t ajc/bibliotek:boot .'
                }
            }
        }

        //  stage('Docker Deploy') {
        //      steps {
        //          dir('bibliotek/dockercompose') {
        //              sh 'docker compose up -d --build angular'
        //          }
        //      }
        //  }
    }
}
